name: bookipedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.4.1
  pinput: ^4.0.0
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  custom_timer: ^0.2.3
  syncfusion_flutter_pdfviewer: ^25.1.39
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  gap: ^3.0.1
  http_parser: ^4.0.2
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  

flutter:
  uses-material-design: true
  
 
  assets:
    - assets/
    - assets/images/
